#!/bin/bash
inpt=

while getopts "i:x:y:" OPTION
do
    case $OPTION in
	i)
            inpt=$OPTARG
            ;;
	x)
	    factorx=$OPTARG
	    ;;
	y)
	    factory=$OPTARG
	    ;;
	
    esac
done
    
if [ -n "$inpt" ] && [ -n "$factorx" ] && [ -n "$factory" ]; then
    nm=$(echo $inpt | awk -F".fastq" '{print $1}')
    if [ -f ${nm}_complexity_total.log ]; then
    	rm ${nm}_complexity_total.log
    fi
    if [ -f ${nm}_complexity.log ]; then
    	awk -v myvar=$factorx 'NR % 2 {print $1 * myvar} !(NR % 2) {print $1}'  ${nm}_complexity.log | awk -v myvar=$factory '!(NR % 2) {print $1 * myvar } NR % 2 {print $1}' > ${nm}_complexity_total.log
        complexity_pro.R ${nm}_complexity_total.log $factorx
    else
    END_four=$(cat $inpt | wc -l)
    END=$(($END_four / 4))
    start=$(($END / 10))
    start2=$(($END / 5))
    seqtk sample -s100 $inpt $start | fqdedup -i - -o ${nm}$start.fastq 2>&1 | tee ${nm}_complexity.log
    rm ${nm}$start.fastq
    for j in $(seq $start2 $start $END)
    do
	seqtk sample -s100 $inpt ${j} | fqdedup -i - -o ${nm}_noadap_${j}_dedup.fastq 2>&1 | tee >>${nm}_complexity.log
	rm ${nm}_noadap_${j}_dedup.fastq
    done
    awk -v myvar=$factorx 'NR % 2 {print $1 * myvar} !(NR % 2) {print $1}'  ${nm}_complexity.log | awk -v myvar=$factory '!(NR % 2) {print $1 * myvar } NR % 2 {print $1}' > ${nm}_complexity_total.log
    complexity_pro.R ${nm}_complexity_total.log $factorx
    fi
elif [ -n "$inpt" ]; then
    nm=$(echo $inpt | awk -F".fastq" '{print $1}')
    if [ -f ${nm}_complexity.log ] ; then
    	rm ${nm}_complexity.log
    fi	
    END_four=$(cat $inpt | wc -l)
    END=$(($END_four / 4))
    start=$(($END / 10))
    start2=$(($END / 5))
    seqtk sample -s100 $inpt $start | fqdedup -i - -o ${nm}$start.fastq 2>&1 | tee ${nm}_complexity.log
    rm ${nm}$start.fastq
    for j in $(seq $start2 $start $END)
    do
	seqtk sample -s100 $inpt ${j} | fqdedup -i - -o ${nm}_noadap_${j}_dedup.fastq 2>&1 | tee >>${nm}_complexity.log
	rm ${nm}_noadap_${j}_dedup.fastq
    done
    complexity_pro.R ${nm}_complexity.log
else 
    echo -e "\nPrior to running fqComplexity, you need to install the following dependencies:\nseqtk https://github.com/lh3/seqtk\nfqdedup https://github.com/guertinlab/fqdedup\n\nfqComplexity usage:\n  fqComplexity -i input.fastq -x preprocessing factor -y postprocessing factor\n\n-i input fastq file, with adapter/adapter ligation products removed \n-x a factor for any preprocessing that occurred, such as removing adapter/adapter ligation products\n-y a factor for any postprocessing that occurred\n "
fi
